name: Tests

on:
  - workflow_dispatch
  - push
  - pull_request

jobs:
  ci:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20, 22, 24]

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/package.lock')) }}

      - name: Install dependencies
        run: npm ci

      - name: Build playground
        run: npm run dev:prepare

      - name: Lint
        run: npm run lint

      - name: Check types
        run: npm run types

      - name: Run tests
        run: npm run test

      - name: Upload coverage to Codecov
        if: github.actor != 'dependabot[bot]'
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage/lcov.info

      - name: Automatically merge dependabot updates
        if: github.event_name == 'pull_request'
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.DEPENDABOT_AUTOMERGE }}
